name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Install Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget tar unzip
        yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
        yes | sdkmanager "platforms;android-34" "build-tools;34.0.0"

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --info

    - name: List build outputs
      run: ls -R app/build/outputs || echo "No outputs found"

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: ToDoWidget-APK
        path: app/build/outputs/apk/debug/app-debug.apk
